# Config for Air (auto reload)
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "tmp/main.exe"
  full_bin = ""
  exclude_dir = ["assets", "tmp", "frontend", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_ext = ["go.sum", "go.mod"]
  follow_symlink = true
  exclude_regex = ["_test.go"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"

[misc]
  clean_on_exit = true
